### ISSUE TITLE
Unhandled exception crashes

### ISSUE THREAD

**Issue by SoundBoomer** [exurd/alcubierre#13]
Using this tool for welcome grinding, and after around 500 places the script crashes. Using Windows 10, Bloxstrap and compiled .exe version of alcubierre
![cmd_eh50rX8Yms](https://github.com/user-attachments/assets/74181c1d-aeb2-46e6-bd9f-47a700807ff0)

**Comment by exurd** [comment]
I know why it crashed because the place information was in a different format than the code expected.
https://github.com/exurd/alcubierre/blob/c6ef903a82bde4bfa4cba8958d7aaf29e2fe63cf/modules/api_reqs.py#L177

However, I don't know the API's response that caused it to crash. Verbose printing would show that.

If you can, please replicate this bug with the `--very-verbose` option (`-vv`) and upload the screenshot here.

**Comment by SoundBoomer** [comment]
Line 3326: www.roblox.com/badges/2124535731
Detecting type from string...
Checking patterns for type: PLACE
Pattern: re.compile('roblox\\.com/games/(\\d+)', re.IGNORECASE)
Pattern: re.compile('place\\?id=(\\d+)', re.IGNORECASE)
Pattern: re.compile('roblox\\.com/Place\\.aspx\\?ID=(\\d+)', re.IGNORECASE)
Pattern: re.compile('roblox\\.com/PlaceItem\\.aspx\\?id=(\\d+)', re.IGNORECASE)
Checking patterns for type: BADGE
Pattern: re.compile('roblox\\.com/badges/(\\d+)', re.IGNORECASE)
RbxInstance [id: 2124535731, type: BADGE]
line_rbxinstance: RbxInstance [id: 2124535731, type: BADGE]
Getting info for 2124535731 with type BADGE
Badge Name: You Played!
Traceback (most recent call last):
  File "__main__.py", line 266, in <module>
  File "__main__.py", line 251, in main
  File "modules\script_loop.py", line 354, in start
  File "modules\script_loop.py", line 286, in handle_line
  File "modules\script_loop.py", line 165, in deal_with_rbxinstance
  File "modules\script_loop.py", line 64, in deal_with_badge
  File "modules\api_reqs.py", line 177, in get_place_info
IndexError: list index out of range
[PYI-2436:ERROR] Failed to execute script '__main__' due to unhandled exception!

**Comment by exurd** [comment]
It seems that the log you're giving me is partial. No request logs are visible, yet the pattern detection logs print out?

Can you please try replicating this on the master branch? I added a feature a while back that creates a log file for each action the program takes, regardless of what kind of verbose arguments are set. Upload a compressed log here once it crashes.
